// <auto-generated />
using System;
using Inspection.DbLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Inspection.DbLayer.Migrations
{
    [DbContext(typeof(InspectionDbContext))]
    [Migration("20240223182601_initial setup")]
    partial class initialsetup
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Inspection.DbLayer.DBModel.ClsInspection", b =>
                {
                    b.Property<int>("InspectionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InspectionID"), 1L, 1);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Customer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("InspectionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("InspectorId")
                        .HasColumnType("int");

                    b.Property<string>("Observations")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InspectionID");

                    b.HasIndex("InspectorId");

                    b.ToTable("TxnInspection");
                });

            modelBuilder.Entity("Inspection.DbLayer.DBModel.ClsInspector", b =>
                {
                    b.Property<int>("InspectorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InspectorId"), 1L, 1);

                    b.Property<string>("InspectorName")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("True");

                    b.HasKey("InspectorId");

                    b.ToTable("mstInspector", (string)null);

                    b.HasData(
                        new
                        {
                            InspectorId = 1,
                            InspectorName = "Inspector 1"
                        },
                        new
                        {
                            InspectorId = 2,
                            InspectorName = "Inspector 2"
                        },
                        new
                        {
                            InspectorId = 3,
                            InspectorName = "Inspector 3"
                        });
                });

            modelBuilder.Entity("Inspection.DbLayer.DBModel.ClsInspection", b =>
                {
                    b.HasOne("Inspection.DbLayer.DBModel.ClsInspector", "Inspector")
                        .WithMany("Inspections")
                        .HasForeignKey("InspectorId")
                        .IsRequired();

                    b.Navigation("Inspector");
                });

            modelBuilder.Entity("Inspection.DbLayer.DBModel.ClsInspector", b =>
                {
                    b.Navigation("Inspections");
                });
#pragma warning restore 612, 618
        }
    }
}
